name: npm publish
on:
  release:
    types: [created]
jobs:
  pre-publish-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-node@latest
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
  publish-npm:
    needs: pre-publish-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-node@latest
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci --production
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
