name: status check
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Check if dependencies are up to date
      - run: npm audit
      - name: Linter check
      - run: npm run eslint
      - name: Check browserified version
      - run: npm run build-test